server {
    listen 80;

    # Root folder where build files are stored
    root /usr/share/nginx/html;

    index index.html;

    location / {
        # Try to find file, else fallback to index.html
        try_files $uri /index.html;
    }
}